version: '3.2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - letsencrypt-challenges:/usr/share/nginx/html
      - letsencrypt-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - letsencrypt-challenges:/usr/share/nginx/html
      - letsencrypt-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx

  db:
    container_name: limbus-db
    image: postgres:10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.production
    expose:
      - "5000"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - /home/limbus/dbdump:/limbus/dumps
    env_file: .env
    depends_on:
      - db
    networks:
      - db
      - nginx
    command: venv/bin/gunicorn --bind 0.0.0.0:5000 run:app
    environment:
      VIRTUAL_HOST: bims.abersystemsbiology.co.uk
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: bims.abersystemsbiology.co.uk
      LETSENCRYPT_EMAIL: keo7@aber.ac.uk

volumes:
  nginx-conf:
  nginx-vhost:
  letsencrypt-certs:
  letsencrypt-templates:
  letsencrypt-challenges:
  postgres_data:


networks:
  db:
  nginx:
