name: Docker Image CI (testing)

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download testing environment file.
      run: wget http://users.aber.ac.uk/keo7/.env
    - name: Check to see if works.
      run: ls
    - name: Get scripts in PATH.
      run: source docker_helpers.sh
    - name: Build the LImBuS stack.
      run: limbus-bwd
    - name: Test to see if built correctly and without error.
      run: limbus-test
